// Generated by Supabase via the MCP integration. Regenerate after any
// schema change with the supabase MCP `generate_typescript_types` tool
// (project_id puzdgqqkksegefcrzege) and replace this file verbatim. Do
// not hand-edit, schema changes belong in supabase/migrations/.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      agent_anomalies: {
        Row: {
          channel: string
          client: string
          created_at: string
          delta: string
          direction: string
          id: string
          metric: string
          run_id: string
        }
        Insert: {
          channel: string
          client: string
          created_at?: string
          delta: string
          direction: string
          id?: string
          metric: string
          run_id: string
        }
        Update: {
          channel?: string
          client?: string
          created_at?: string
          delta?: string
          direction?: string
          id?: string
          metric?: string
          run_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "agent_anomalies_run_id_fkey"
            columns: ["run_id"]
            isOneToOne: false
            referencedRelation: "agent_runs"
            referencedColumns: ["id"]
          },
        ]
      }
      agent_feedback: {
        Row: {
          created_at: string
          id: string
          kind: string
          rating: number | null
          run_id: string
          text: string | null
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          kind: string
          rating?: number | null
          run_id: string
          text?: string | null
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          kind?: string
          rating?: number | null
          run_id?: string
          text?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "agent_feedback_run_id_fkey"
            columns: ["run_id"]
            isOneToOne: false
            referencedRelation: "agent_runs"
            referencedColumns: ["id"]
          },
        ]
      }
      agent_images: {
        Row: {
          composition: string | null
          created_at: string
          id: string
          image_storage_path: string | null
          image_url: string | null
          palette_from: string | null
          palette_to: string | null
          run_id: string
          title: string
          virality_score: number | null
        }
        Insert: {
          composition?: string | null
          created_at?: string
          id?: string
          image_storage_path?: string | null
          image_url?: string | null
          palette_from?: string | null
          palette_to?: string | null
          run_id: string
          title: string
          virality_score?: number | null
        }
        Update: {
          composition?: string | null
          created_at?: string
          id?: string
          image_storage_path?: string | null
          image_url?: string | null
          palette_from?: string | null
          palette_to?: string | null
          run_id?: string
          title?: string
          virality_score?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "agent_images_run_id_fkey"
            columns: ["run_id"]
            isOneToOne: false
            referencedRelation: "agent_runs"
            referencedColumns: ["id"]
          },
        ]
      }
      agent_memory: {
        Row: {
          agent_id: string
          applied_count: number
          created_at: string
          id: string
          rule: string
          source: string | null
          source_feedback_id: string | null
        }
        Insert: {
          agent_id: string
          applied_count?: number
          created_at?: string
          id?: string
          rule: string
          source?: string | null
          source_feedback_id?: string | null
        }
        Update: {
          agent_id?: string
          applied_count?: number
          created_at?: string
          id?: string
          rule?: string
          source?: string | null
          source_feedback_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "agent_memory_agent_id_fkey"
            columns: ["agent_id"]
            isOneToOne: false
            referencedRelation: "agents"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "agent_memory_source_feedback_id_fkey"
            columns: ["source_feedback_id"]
            isOneToOne: false
            referencedRelation: "agent_feedback"
            referencedColumns: ["id"]
          },
        ]
      }
      agent_memory_kv: {
        Row: {
          created_at: string
          id: string
          payload: Json
          scope: string
          slice: string
        }
        Insert: {
          created_at?: string
          id?: string
          payload: Json
          scope: string
          slice: string
        }
        Update: {
          created_at?: string
          id?: string
          payload?: Json
          scope?: string
          slice?: string
        }
        Relationships: []
      }
      agent_reports: {
        Row: {
          body_md: string | null
          created_at: string
          excerpt: string | null
          id: string
          metrics_json: Json | null
          run_id: string
          title: string
        }
        Insert: {
          body_md?: string | null
          created_at?: string
          excerpt?: string | null
          id?: string
          metrics_json?: Json | null
          run_id: string
          title: string
        }
        Update: {
          body_md?: string | null
          created_at?: string
          excerpt?: string | null
          id?: string
          metrics_json?: Json | null
          run_id?: string
          title?: string
        }
        Relationships: [
          {
            foreignKeyName: "agent_reports_run_id_fkey"
            columns: ["run_id"]
            isOneToOne: false
            referencedRelation: "agent_runs"
            referencedColumns: ["id"]
          },
        ]
      }
      agent_runs: {
        Row: {
          agent_id: string
          client: string | null
          completed_at: string | null
          error: string | null
          id: string
          input: Json | null
          note: string | null
          output: Json | null
          progress: number | null
          rating: number | null
          score: number | null
          started_at: string
          status: string
          step: string | null
        }
        Insert: {
          agent_id: string
          client?: string | null
          completed_at?: string | null
          error?: string | null
          id?: string
          input?: Json | null
          note?: string | null
          output?: Json | null
          progress?: number | null
          rating?: number | null
          score?: number | null
          started_at?: string
          status: string
          step?: string | null
        }
        Update: {
          agent_id?: string
          client?: string | null
          completed_at?: string | null
          error?: string | null
          id?: string
          input?: Json | null
          note?: string | null
          output?: Json | null
          progress?: number | null
          rating?: number | null
          score?: number | null
          started_at?: string
          status?: string
          step?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "agent_runs_agent_id_fkey"
            columns: ["agent_id"]
            isOneToOne: false
            referencedRelation: "agents"
            referencedColumns: ["id"]
          },
        ]
      }
      agents: {
        Row: {
          avatar_url: string
          created_at: string
          description: string
          id: string
          name: string
          paused: boolean
          role: string
          schedule: string
        }
        Insert: {
          avatar_url: string
          created_at?: string
          description: string
          id: string
          name: string
          paused?: boolean
          role: string
          schedule: string
        }
        Update: {
          avatar_url?: string
          created_at?: string
          description?: string
          id?: string
          name?: string
          paused?: boolean
          role?: string
          schedule?: string
        }
        Relationships: []
      }
      ask_queries: {
        Row: {
          answered_by: string | null
          chart_config_json: Json | null
          chart_type: string | null
          client_id: string | null
          created_at: string
          date_range_end: string | null
          date_range_start: string | null
          id: string
          language: string
          query_text: string
          result_json: Json | null
          user_id: string
        }
        Insert: {
          answered_by?: string | null
          chart_config_json?: Json | null
          chart_type?: string | null
          client_id?: string | null
          created_at?: string
          date_range_end?: string | null
          date_range_start?: string | null
          id?: string
          language?: string
          query_text: string
          result_json?: Json | null
          user_id: string
        }
        Update: {
          answered_by?: string | null
          chart_config_json?: Json | null
          chart_type?: string | null
          client_id?: string | null
          created_at?: string
          date_range_end?: string | null
          date_range_start?: string | null
          id?: string
          language?: string
          query_text?: string
          result_json?: Json | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "ask_queries_answered_by_fkey"
            columns: ["answered_by"]
            isOneToOne: false
            referencedRelation: "agents"
            referencedColumns: ["id"]
          },
        ]
      }
      pinned_tiles: {
        Row: {
          chart_config_json: Json
          created_at: string
          id: string
          position_index: number
          question: string | null
          source: string
          source_query_id: string | null
          title: string
          user_id: string
        }
        Insert: {
          chart_config_json: Json
          created_at?: string
          id?: string
          position_index?: number
          question?: string | null
          source: string
          source_query_id?: string | null
          title: string
          user_id: string
        }
        Update: {
          chart_config_json?: Json
          created_at?: string
          id?: string
          position_index?: number
          question?: string | null
          source?: string
          source_query_id?: string | null
          title?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "pinned_tiles_source_query_id_fkey"
            columns: ["source_query_id"]
            isOneToOne: false
            referencedRelation: "ask_queries"
            referencedColumns: ["id"]
          },
        ]
      }
      reports: {
        Row: {
          agent_run_id: string | null
          audit: Json
          authored_by: string
          client: string
          client_label: string
          closing: Json
          cover: Json
          created_at: string
          filter_range: string | null
          id: string
          owner_user_id: string
          period: string
          period_end: string | null
          period_start: string | null
          prompt: string | null
          sections: Json
          shared_with: Json
          source: string
          status: string
          title: string
          updated_at: string
        }
        Insert: {
          agent_run_id?: string | null
          audit?: Json
          authored_by?: string
          client: string
          client_label: string
          closing?: Json
          cover?: Json
          created_at?: string
          filter_range?: string | null
          id: string
          owner_user_id: string
          period: string
          period_end?: string | null
          period_start?: string | null
          prompt?: string | null
          sections?: Json
          shared_with?: Json
          source?: string
          status?: string
          title: string
          updated_at?: string
        }
        Update: {
          agent_run_id?: string | null
          audit?: Json
          authored_by?: string
          client?: string
          client_label?: string
          closing?: Json
          cover?: Json
          created_at?: string
          filter_range?: string | null
          id?: string
          owner_user_id?: string
          period?: string
          period_end?: string | null
          period_start?: string | null
          prompt?: string | null
          sections?: Json
          shared_with?: Json
          source?: string
          status?: string
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "reports_agent_run_id_fkey"
            columns: ["agent_run_id"]
            isOneToOne: false
            referencedRelation: "agent_runs"
            referencedColumns: ["id"]
          },
        ]
      }
      rag_chunks: {
        Row: {
          chunk_id: string
          content: string
          corpus: string
          created_at: string
          embedding: string
          id: string
          metadata: Json
          source_path: string
          updated_at: string
        }
        Insert: {
          chunk_id: string
          content: string
          corpus: string
          created_at?: string
          embedding: string
          id?: string
          metadata?: Json
          source_path: string
          updated_at?: string
        }
        Update: {
          chunk_id?: string
          content?: string
          corpus?: string
          created_at?: string
          embedding?: string
          id?: string
          metadata?: Json
          source_path?: string
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
